[Settings]
ID = "utils-gg"

[build]
  publish = "dist/"
  command = "npm start build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://utils-gg.netlify.com/*"
  to = "https://utils.gg/:splat"
  status = 301
